"""FIREWATCH ontology — the single source of truth (objects · links · actions).

See docs/ONTOLOGY.md. Modules read/write these objects; they never exchange raw feed payloads.
"""
from firewatch.ontology.actions import acknowledge, ingest_observation, override
from firewatch.ontology.objects import (
    OBJECT_TYPES,
    Camera,
    Fire,
    FirePerimeter,
    FireStatus,
    Forecast,
    FuelCell,
    Observation,
    ObservationKind,
    OntologyObject,
    PerimeterSource,
    PopulationZone,
    Provenance,
    Recommendation,
    RecommendationKind,
    Resource,
    ResourceKind,
    RoadSegment,
    Structure,
    TerrainCell,
    WeatherCell,
    new_id,
    utcnow,
)
from firewatch.ontology.store import Store

__all__ = [
    "OBJECT_TYPES",
    "Camera",
    "Fire",
    "FirePerimeter",
    "FireStatus",
    "Forecast",
    "FuelCell",
    "Observation",
    "ObservationKind",
    "OntologyObject",
    "PerimeterSource",
    "PopulationZone",
    "Provenance",
    "Recommendation",
    "RecommendationKind",
    "Resource",
    "ResourceKind",
    "RoadSegment",
    "Store",
    "Structure",
    "TerrainCell",
    "WeatherCell",
    "acknowledge",
    "ingest_observation",
    "new_id",
    "override",
    "utcnow",
]
