"""Evaluation figures + metrics (docs/EVALUATION.md), regenerated by `make demo` / `make replay`.

Produces the headline artifacts: the assimilation ON-vs-OFF ablation, the reliability diagram
(pre/post recalibration), the "forecast sharpens as observations arrive" curve, and a static COP
preview map. All figures come from pinned inputs so they are reproducible.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from firewatch.config import EventPaths
from firewatch.forecast.calibrate import (
    brier_score,
    coverage,
    expected_calibration_error,
    fit_temperature,
    reliability_curve,
    temperature_scale,
)
from firewatch.forecast.spread import burned_mask

# consistent, legible dark-on-light palette
_ON = "#e4572e"
_OFF = "#8a8d91"
_ACC = "#2e6fb0"


def generate_figures(bundle, result: dict, sharpening: list[dict] | None = None) -> dict:
    paths = EventPaths(bundle.event_id).ensure()
    figdir = paths.outputs / "figures"
    figdir.mkdir(parents=True, exist_ok=True)
    on = result["forecast_on"]
    truth = bundle.truth_arrival
    out: dict = {"figures": {}, "metrics": {}}

    # 1. ablation bar (IoU ON vs OFF)
    if truth is not None and "skill_on" in result:
        so, sf = result["skill_on"], result["skill_off"]
        hs = on.horizons
        x = np.arange(len(hs))
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.bar(x - 0.2, [sf[h]["iou"] for h in hs], 0.4, label="assimilation OFF (baseline)", color=_OFF)
        ax.bar(x + 0.2, [so[h]["iou"] for h in hs], 0.4, label="assimilation ON", color=_ON)
        ax.set_xticks(x, [f"+{h}m" for h in hs])
        ax.set_ylabel("perimeter IoU vs truth")
        ax.set_title("Assimilation ablation, the thesis (synthetic replay)")
        ax.legend()
        ax.grid(axis="y", alpha=0.3)
        fig.tight_layout()
        p = figdir / "ablation_iou.png"
        fig.savefig(p, dpi=130)
        plt.close(fig)
        out["figures"]["ablation"] = str(p)
        out["metrics"]["ablation"] = {
            str(h): {"iou_on": so[h]["iou"], "iou_off": sf[h]["iou"], "dice_on": so[h]["dice"], "dice_off": sf[h]["dice"]}
            for h in hs
        }

    # 2. reliability diagram (pre/post temperature scaling)
    if truth is not None:
        h = on.horizons[len(on.horizons) // 2]
        p = on.prob_fields[h].ravel()
        y = burned_mask(truth, h).ravel().astype(float)
        T = fit_temperature(p, y)
        p_cal = temperature_scale(p, T)
        rc = reliability_curve(p, y, 10)
        rc2 = reliability_curve(p_cal, y, 10)
        fig, ax = plt.subplots(figsize=(5.2, 5))
        ax.plot([0, 1], [0, 1], "--", color="#999", label="perfect")
        ax.plot(rc.pred_mean, rc.obs_freq, "o-", color=_OFF, label=f"raw (Brier {brier_score(p, y):.3f})")
        ax.plot(rc2.pred_mean, rc2.obs_freq, "o-", color=_ON, label=f"T-scaled (T={T:.2f}, Brier {brier_score(p_cal, y):.3f})")
        ax.set_xlabel("predicted burn probability")
        ax.set_ylabel("observed burn frequency")
        ax.set_title(f"Reliability @ +{h} min")
        ax.legend(fontsize=8)
        ax.set_aspect("equal")
        fig.tight_layout()
        pth = figdir / "reliability.png"
        fig.savefig(pth, dpi=130)
        plt.close(fig)
        out["figures"]["reliability"] = str(pth)
        out["metrics"]["calibration"] = {
            "horizon": h, "temperature": T,
            "brier_raw": brier_score(p, y), "brier_calibrated": brier_score(p_cal, y),
            "ece_raw": expected_calibration_error(p, y), "ece_calibrated": expected_calibration_error(p_cal, y),
            "coverage": coverage(on.prob_fields[h], burned_mask(truth, h)),
        }

    # 3. sharpening curve
    if sharpening:
        xs = [s["issue_min"] for s in sharpening]
        area = [s["region90_area_km2"] for s in sharpening]
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.plot(xs, area, "o-", color=_ACC, label="90% region area")
        ax.set_xlabel("forecast issue time (min since ignition)")
        ax.set_ylabel("90% region area (km²)")
        ax.set_title("Forecast sharpens as observations arrive")
        if all("iou" in s for s in sharpening):
            ax2 = ax.twinx()
            ax2.plot(xs, [s["iou"] for s in sharpening], "s--", color=_ON, label="IoU vs truth")
            ax2.set_ylabel("IoU vs truth", color=_ON)
        fig.tight_layout()
        pth = figdir / "sharpening.png"
        fig.savefig(pth, dpi=130)
        plt.close(fig)
        out["figures"]["sharpening"] = str(pth)
        out["metrics"]["sharpening"] = sharpening

    # 4. static COP preview map
    out["figures"]["cop_map"] = _cop_map(bundle, on, figdir)

    (paths.outputs / "metrics.json").write_text(json.dumps(out["metrics"], indent=2, default=str))
    out["metrics_path"] = str(paths.outputs / "metrics.json")
    return out


def _cop_map(bundle, on, figdir: Path) -> str:
    grid = bundle.grid
    fig, ax = plt.subplots(figsize=(7.5, 7))
    ax.imshow(grid.fuel, origin="lower", cmap="YlOrBr", alpha=0.35,
              extent=[grid._xs[0], grid._xs[-1], grid._ys[0], grid._ys[-1]])
    proj = grid.projector

    def draw(geom, **kw):
        if geom is None:
            return
        polys = geom.geoms if geom.geom_type == "MultiPolygon" else [geom]
        for pg in polys:
            if pg.is_empty or not hasattr(pg, "exterior"):
                continue
            xs, ys = proj.to_local(*np.asarray(pg.exterior.coords).T)
            ax.plot(xs, ys, **kw)

    h = max(on.horizons)
    draw(on.region_90.get(h), color=_ACC, lw=1.2, alpha=0.7)
    draw(on.expected_perimeter.get(h), color=_ON, lw=2)
    if bundle.truth_arrival is not None:
        draw(grid.mask_to_polygon(burned_mask(bundle.truth_arrival, h)), color="k", lw=1.5, ls="--")
    for z in bundle.zones:
        draw(z.geom(), color="#3a7", lw=1.5)
    ix, iy = proj.to_local(*bundle.ignition_lonlat)
    ax.plot(ix, iy, "*", color="red", ms=16)
    ax.set_title(f"COP preview @ +{h} min  (red=expected, blue=90% region, dashed=truth, green=zones)")
    ax.set_xlabel("meters E")
    ax.set_ylabel("meters N")
    fig.tight_layout()
    p = figdir / "cop_map.png"
    fig.savefig(p, dpi=130)
    plt.close(fig)
    return str(p)
